### ISSUE TITLE
Move from Todo.md to Issues

### ISSUE THREAD

**Issue by TessyPowder** [SchoolSquirrel/SchoolSquirrel#6]
A Todo File is definitely a good start for brainstorming, but shouldn't we start to use issues ?

**Comment by hrueger** [comment]
Sure, feel free to create them!

**Comment by TessyPowder** [comment]
I created all issues. Should i delete the markdown file ?

**Comment by hrueger** [comment]
👍

**Comment by TessyPowder** [comment]
i deleted the Todo file
